### ISSUE TITLE
Option for better reverse geocoding

### ISSUE THREAD

**Issue by trishmapow** [trishmapow/nordvpn-tools#2]
reverse_geocode library is OK but is not very accurate and misses smaller cities

**Comment by zedstar** [comment]
I cannot even get it to work with large cities like 'New York, United States'

would be good to get some sort of reference to lookup. When i use a tool such as - https://www.latlong.net/c/?lat=40.755931&long=-73.984606 
it spits out the true address such as " 124 West 43rd Street, New York, NY 10036
Times Square, New York, Midtown New York, Manhattan New York United States"

Using 'New York, United States' fails to pickup. please advise.

**Comment by trishmapow** [comment]
Yep this is a known issue, I only found out recently there is a v1 API https://api.nordvpn.com/v1/servers which has city named servers. This will be in the next update (soonish) - shouldn't be too hard to patch in.

(I would prefer to not have to use another online service because API keys etc is a pain)

**Comment by zedstar** [comment]
nice one - keep up the good work :)

**Comment by trishmapow** [comment]
Just pushed a rewrite using the new API, was a real pain to reverse engineer. Enjoy! Let me know if there's any other suggestions.
